###
GET http://localhost:5000/users

### register
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Arsy Madya Budianto",
    "email": "amb@gmail.com",
    "password": "32143",
    "confPassword": "32143"	
}

### login
POST http://localhost:5000/login
Content-Type: application/json

{
    // "email": "amb@gmail.com",
    // "password": "32143"
    "email": "amd@gmail.com",
    "password": "1234"
}

### login with access key
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJuYW1lIjoiQW1kIE1pc2MiLCJlbWFpbCI6ImFtZEBnbWFpbC5jb20iLCJpYXQiOjE2ODY3NDM5NzUsImV4cCI6MTY4Njc1ODM3NX0.KqeWhU5EHn8VbOuyhk2L_CdsPmJc8aYno7THhDLMdDw

### updating expired access key
GET http://localhost:5000/token

### log out and delete access key
DELETE http://localhost:5000/logout